### ISSUE TITLE
[ATELIER UX] - Ajout de l'objet du marché dans le tableau des marchés d'un acheteur

### ISSUE THREAD

**Issue by lvinsonneau** [collec-data/focus-marches#1]
Les acheteurs interrogés en atelier UX design ont fait remonter le besoin de disposer de l'objet du marché dans le tableau d'un acheteur.
Ils sont même prêts à "perdre" l'information du code CPV si un problème de place se pose  : 
C'est sur cette page par exemple : https://data.megalis.bretagne.bzh/focus-marches/acheteur.php?i=25351449100047 (graphique : Tous les marchés de MEGALIS BRETAGNE)
![image](https://github.com/collec-data/focus-marches/assets/2498403/41d16ccb-4e1a-448a-8591-8791faf753ef)

**Comment by VictorVila** [comment]
Pourquoi pas les deux ? 

Voici ce que ça peut donner (local) : 
![image](https://github.com/collec-data/focus-marches/assets/2961426/8771c6d3-654b-493e-a33a-eb96df1ccb40)

Note fichiers impactés : 

- /data/getRecherche.php
- /titulaire.php

**Comment by lvinsonneau** [comment]
Discussion PSC : OK pour les 2 et on réduit les marges blanches sur le côté
