### ISSUE TITLE
Recherche avancée - Ajouter une iframe 

### ISSUE THREAD

**Issue by barbitruc** [collec-data/focus-marches#12]
Bonjour, 

Serait-il possible d'ajouter une iframe après avoir fait une recherche avancée ? Par exemple si je veux publier sur mon site les données de l'année en cours.

**Comment by ARNiAamo** [comment]
Bonjour, 
L'idée est intéressante. Pour que cela soit possible il faudrait que les paramètres de la recherche en question soient stockés dans l'URL de l'iframe et que la page de recherche y accède.
Actuellement la page de recherche ne se sert pas d'éventuels paramètres dans l'URL pour fonctionner, mais techniquement on devrait pouvoir ajouter cette fonctionnalité sans trop refaire l'existant.
A prioriser en fonction du potentiel d'utilisation.

**Comment by lvinsonneau** [comment]
Discussion PSC : cela demande un peu de temps en développement. @barbitruc : peux-tu nous nous préciser le besoin : s'agit-il d'avoir au bout du compte une filtre par année ?

**Comment by barbitruc** [comment]
Oui effectivement ça revient à ça. Le besoin d'origine c'était de pouvoir valoriser les données par année et non pas sur 33 mois.

**Comment by lvinsonneau** [comment]
Au final, ce ticket n'est-il pas un doublon du #9 ?

**Comment by lvinsonneau** [comment]
doublon, je clos le ticket le filtre par date a été déployé
