### ISSUE TITLE
Pistes pour des nouveaux indicateurs

### ISSUE THREAD

**Issue by VictorVila** [collec-data/focus-marches#13]
Bonjour, 
Au GT indicateurs achat durable on a vu ces pistes pour des nouveaux indicateurs :

![image](https://github.com/collec-data/focus-marches/assets/2961426/3a94a050-e103-49f8-b879-c80a7ae74f40)

/!\ Attention néanmoins aux données relatives aux [ESS ](https://www.economie.gouv.fr/cedef/economie-sociale-et-solidaire) car elles peuvent ne pas être fiables (déclaration volontaire de l'entreprise).

![image](https://github.com/collec-data/focus-marches/assets/2961426/5bb9c0e7-4aba-482c-85d0-f181977b7ea6)

![image](https://github.com/collec-data/focus-marches/assets/2961426/09e07119-5862-43e0-983c-13672119a10e)

![image](https://github.com/collec-data/focus-marches/assets/2961426/5a503565-9f50-492b-9e02-f849d94465bd)

![image](https://github.com/collec-data/focus-marches/assets/2961426/9c2b2ccb-6183-40bb-a0d2-7fc471133e2f)

![image](https://github.com/collec-data/focus-marches/assets/2961426/cfe3691a-ee77-436c-99df-fb4e0c354c5a)

**Comment by VictorVila** [comment]
5 février 2024 : présentation d'une version liminaire par Raphaël Joblot 

Pistes proposées : 

- Afficher la donnée de manière simple sur le tableau de bord de chaque acheteur
- Proposer une vue dans le menu (PNAD ?) dont le contenu permettrait : 
1. Regrouper à différents niveaux administratifs pour trouver la strate qui fait du sens pour l'analyse
2. Permettre aux acheteurs de se comparer (définir par rapport à quoi)
3. Agréger les données par les 17 secteurs d'achat identifiés

**Comment by lvinsonneau** [comment]
Remplacé par le prototype suite à l'atelier UX (#60)
