### ISSUE TITLE
Données doublonnées sur Focus marchés ?

### ISSUE THREAD

**Issue by lvinsonneau** [collec-data/focus-marches#17]
Je vous relaye un problème soulevé par une de nos utilisatrices auquel je ne trouve pas d'explication (c'est peut-être lié au notion d'accord cadre que je ne maîtrise pas ?) 

La collectivité dispose de **deux contrats sur la salle des marchés** : 
![image](https://github.com/collec-data/focus-marches/assets/2498403/712de945-980b-4602-8b1a-176cfbac7954)

Sur le **xml de data gouv**, je retrouve bien les **deux marchés** : 
` <marche>
    <id>20222022S0001500</id>
    <acheteur>
      <id>24350055000153</id>
      <nom>MONTFORT COMMUNAUTE </nom>
    </acheteur>
    <nature>Accord-cadre</nature>
    <typeContrat>MARCHE_PUBLIC</typeContrat>
    <objet>Prestations de nettoyage des locaux et des vitres des bâtiments communautaires. - Prestations de nettoyage des locaux</objet>
    <codeCPV>90911200</codeCPV>
    <procedure>Appel d'offres ouvert</procedure>
    <lieuExecution>
      <code>35</code>
      <typeCode>Code département</typeCode>
      <nom>(35) Ille-et-Vilaine</nom>
    </lieuExecution>
    <dureeMois>36</dureeMois>
    <dateNotification>2022-10-14</dateNotification>
    <datePublicationDonnees>2022-10-14</datePublicationDonnees>
    <montant>172818.0</montant>
    <formePrix>Révisable</formePrix>
    <titulaires>
      <titulaire>
        <typeIdentifiant>SIRET</typeIdentifiant>
        <id>34448300300218</id>
        <denominationSociale>GSF CELTUS</denominationSociale>
      </titulaire>
    </titulaires>
    <uuid>A71041A3-128F-42CA-B3A9-9E0EFDB7F089</uuid>
  </marche>
  <marche>
    <id>20222022S0001700</id>
    <acheteur>
      <id>24350055000153</id>
      <nom>MONTFORT COMMUNAUTE </nom>
    </acheteur>
    <nature>Accord-cadre</nature>
    <typeContrat>MARCHE_PUBLIC</typeContrat>
    <objet>Prestations de nettoyage des locaux et des vitres des bâtiments communautaires. - Prestations de nettoyage des vitres</objet>
    <codeCPV>90911300</codeCPV>
    <procedure>Appel d'offres ouvert</procedure>
    <lieuExecution>
      <code>35</code>
      <typeCode>Code département</typeCode>
      <nom>(35) Ille-et-Vilaine</nom>
    </lieuExecution>
    <dureeMois>36</dureeMois>
    <dateNotification>2022-10-14</dateNotification>
    <datePublicationDonnees>2022-10-14</datePublicationDonnees>
    <montant>9811.0</montant>
    <formePrix>Révisable</formePrix>
    <titulaires>
      <titulaire>
        <typeIdentifiant>SIRET</typeIdentifiant>
        <id>34448300300218</id>
        <denominationSociale>GSF CELTUS</denominationSociale>
      </titulaire>
    </titulaires>
    <uuid>D923DF9D-6E2E-43DF-B586-42A26C1E71E4</uuid>
  </marche>`

Et **sur Focus marchés**, on retrouve des informations en trop (https://data.megalis.bretagne.bzh/focus-marches/acheteur.php?i=24350055000153 page 4) : 
![image](https://github.com/collec-data/focus-marches/assets/2498403/79add9ad-e593-4ff9-a066-d2d6a0af65cf)

@yguenneugues et/ou @VictorVila : voyez-vous une explication ?

**Comment by yguenneugues** [comment]
L'unicité des marchés est réalisée avec le champ uuid présent dans le bloc marche du fichier decp.

Pour l'exemple ci-dessus, j'ai regardé en base de données et il y a a bien deux uuid différents (colonne id_marche dans la screen ci-dessous), cela explique les marches en doublons dans l'interface de focus marche.
![image](https://github.com/collec-data/focus-marches/assets/10934427/ad80447e-7431-4af0-bf55-2ab64edad5a1)

- Est il possible qu'un marché ( uuid) soit supprimé d'un fichier decp ?
- Est il possible qu'un uuid soit modifié ? 

Actuellement l'import fonctionne en mode incrémentale. La bdd n'est pas supprimée tous les jours.
On recherche si on a déjà le marche dans notre bdd en utilisant l'uuid, si oui on le met à jour sinon on crée le marche.
On ne supprime pas les marchés déjà importé qu'on aurait pas retrouvé dans les xml.

Une solution au problème rencontré est de réaliser un import full. On vide toute la bdd avant de faire l'import quotidien des marches.

**Comment by lvinsonneau** [comment]
Bonjour @yguenneugues : je parle sous couvert de @Cridard et @barbitruc, mais je dirais que "Oui, une uuid peut être modifié et/ou supprimé.
 Cela expliquerait les choses.

@yguenneugues : Quel(s) impact(s) pour la mise en place d'un import full ? performances ?

**Comment by yguenneugues** [comment]
ça sera forcement moins performant mais pas gênant. ( à la place de prendre 1min ça va prendre 5 min, c'est un ordre de grandeur)

Je vais limiter la purge aux marches et garder les infos sur les siren pour ne pas avoir à rappeler l'api entreprise tous les jours pour l'ensemble des organisations et entreprises.

**Comment by lvinsonneau** [comment]
OK. 
@VictorVila : ça te va aussi côté ARNia ce mode de fonctionnement ?

**Comment by yguenneugues** [comment]
version installée en preprod megalis avec import des même données qu'en prod : https://data-preprod.megalis.bretagne.bzh/focus-marches/

**Comment by VictorVila** [comment]
@lvinsonneau : oui tout à fait d'accord. Je n'ai pas encore pu voir le code de Yann mais dans ce volume de données l'import complet n'est pas très impactant.

@yguenneugues : merci pour ton travail ! Je vais essayer de me caler du temps pour regarder le code.

**Comment by yguenneugues** [comment]
version installée en production chez megalis
