### ISSUE TITLE
PROD - retour arrière (dézoom) sur le graphique "Nature des contrats" KO

### ISSUE THREAD

**Issue by ElodieTessier** [collec-data/focus-marches#18]
Bonjour,
le retour arrière (dézoom en double cliquant) sur le graphique "Nature des contrats" KO
![image](https://github.com/collec-data/focus-marches/assets/97222408/131ae61b-022c-40a9-9195-3e8b815e058d)

**Comment by lvinsonneau** [comment]
Discussion PSC : @ElodieTessier : en fait, il suffit de double-cliquer sur le graphique (un message l'indiquant s'affiche en haut à droite)
