### ISSUE TITLE
GitFlow - Définition du flux de travail entre partenaires

### ISSUE THREAD

**Issue by VictorVila** [collec-data/focus-marches#25]
Nous avons évoqué en PSC la question du travail en branches parallèles. 

La piste évoquée est d'utiliser le système proposé par **Gitflow**. Ce flux est défini p.ex. sur cette page http://datasift.github.io/gitflow/IntroducingGitFlow.html qui fait bien apparaître une branche développement comme proposé par @yguenneugues .

![Image](https://github.com/collec-data/focus-marches/assets/2961426/a3c867bc-d94e-415b-bc9c-10a30117e978)

L'objectif maintenant est de nous doter d'une référence commune qui remplacerait la gouvernance tel quelle définie initialement avec Sébastien et Lydie : 
![Image](https://github.com/collec-data/focus-marches/assets/2961426/83bebd6e-7d7d-4ca8-9953-bbcfebdfcf78)

En tant que spécialistes du sujet, @QalvesGip  @yguenneugues @syji35 pourriez-vous identifier un document de référence de GitFlow ?

**Comment by syji35** [comment]
Gitflow est un modèle de gestion de branches Git très courant et utilisé dans de nombreux projets.

On peut trouver une définition du modèle ici (avec des exemples) : [Lien vers le tutoriel Gitflow d'Atlassian](https://www.atlassian.com/fr/git/tutorials/comparing-workflows/gitflow-workflow#:~:text=Gitflow%20est%20l'un%20des,les%20hotfix%20vers%20la%20production).

Pour moi, il semble suffisant de se baser sur ce modèle, sans avoir à en inventer un autre.

Ensuite, là où il y a discussion, c'est sur le paramétrage du dépôt Git Collect-data/Focus -marché.

Quand une Pull Request arrive sur le GitHub (peu importe l'origine), au moins une personne (@QalvesGip, @syji35, @VictorVila ou @yguenneugues) doit relire et valider la Pull Request avant de la fusionner dans la branche "develop". 
On peut même faire en sorte que tout le monde doit relire la Pull Request.

J'ai également veillé à ce que personne ne puisse effectuer de commit/push sur les branches master et develop.

En ce qui concerne les Pull Requests, nous pouvons également mettre en place un contrôle automatique du code avec Codacy (c'est d'ailleurs l'objet de la Pull Request suivante : [Lien vers la Pull Request sur GitHub](https://github.com/collec-data/focus-marches/pull/22)).

Enfin, nous pouvons automatiser la construction d'une image Docker à partir du GitHub chaque fois que nous publions une nouvelle version (un nouveau tag dans le Gitflow).

**Comment by VictorVila** [comment]
Décision : 2 personnes doivent valider chaque pull request 
Bonne pratique : prévenir les autres sur Gitter qu'on va valider la pull request
