### ISSUE TITLE
Atelier UX : Fonctionnalités liées au nouveau schéma de données

### ISSUE THREAD

**Issue by VictorVila** [collec-data/focus-marches#27]
Attendre à avoir des données pour avoir un bac à sable > maxi mars/2024 (Raphaël, Florian, Lydie, Elodie, Thierry, Victor)
- Informations sur les sous-traitants de l'acte initial
S'inspirer des expériences "Actes"
Possible de le faire dans 1/2 journée

To do : fixer une date

**Comment by lvinsonneau** [comment]
on clôture suite à atelier UX et PSC de ce jour
