### ISSUE TITLE
Déporter les templates graphiques (mode Arnia, megalis etc...)

### ISSUE THREAD

**Issue by VictorVila** [collec-data/focus-marches#29]
Au moment de la configuration choisir le dossier contenant son thème (dossier /ui/personnalisation/).
Un thème par défaut est disponible.

**Comment by VictorVila** [comment]
Sylvain se propose de le tester

**Comment by lvinsonneau** [comment]
@syji35 : tu as pu le tester ?

**Comment by lvinsonneau** [comment]
(je dis ça car l'issue apparait tjs dans notre tableau projet dans la colonne "à tester"
![Image](https://github.com/user-attachments/assets/98ff20da-9b68-49d8-b868-fd1559915461)
)
