### ISSUE TITLE
[ATELIER UX] - Absence des accords cadres déplorée

### ISSUE THREAD

**Issue by lvinsonneau** [collec-data/focus-marches#3]
Les acheteurs interrogés en atelier UX design ont fait remonter le souhait de voir les accords-cadres intégrer Focus marchés. Selon eux, c'est un frein au dépliement de Focus marchés.

Si ce n'est pas possible, détailler l'argumentaire qui explique que ce n'est pas possible ?
Si cela est possible, détailler ce qu'il manque aujourd'hui pour qu'ils soient présents ?

**Comment by VictorVila** [comment]
On n'a malheureusement pas l'information. Il faut qu'on planche ensemble sur comment contourner ce problème et si le format 2.0 des DECP nous apporte des solutions.
Sinon, on mentionne la problématique sur l'accueil, mais sans doute qu'il faudrait faire ce message plus visible. 
![image](https://github.com/collec-data/focus-marches/assets/2961426/594a4d21-b90c-4eb2-aeec-a112258d4762)

**Comment by yguenneugues** [comment]
Pourtant sur le graphique **nature de contrats** on voit bien les accords cadre:

![image](https://github.com/collec-data/focus-marches/assets/10934427/c758bc4b-8b2a-4b10-bb11-31a2d0927c83)

C'est pourquoi j'ai supprimé la phrase que les accords-cadres sont exclus sur les instances focus-marches de megalis et du recia. Sont-il vraiment exclus ?

**Comment by VictorVila** [comment]
Merci Yann pour avoir pointé ce graphique qui remet sur la table une question importante et un oubli.  

Voici les problématiques que les accords cadres suscitent. Merci à ceux qui ont la compétence métier de corriger :  

1. Le montant affiché par les accords cadres n'est qu'indicatif : les accords cadres affichent un montant qui n'est qu'une estimation de ce qui va / peut être réalisé.  
2. Le montant réel est défini par les marchés subséquents qui sont rattachés à l'accord cadre. 
3. Nous n'avons pas à priori un moyen de relier les marchés subséquents à leur accord cadre. 
Du coup, la grande question est : comment répresenter ces marchés ? 

Le choix, discutable, fait côté ARNiA mais visiblement pas implementé est de ne pas tenir compte des accords cadres. 

A cela s'ajoute un autre sujet : la nature des contrats (dont accord cadre et marché subséquent) ne semble pas correctement saisie dans des nombreux marchés de notre profil d'acheteur.

**Comment by lvinsonneau** [comment]
Discussion PSC : à voir avec le nouveau schéma de données essentielles (format 2022)

**Comment by lvinsonneau** [comment]
Remplacé par l'issue avec le prototype suite à l'atelier UX (#60)
