### ISSUE TITLE
Proposition Logo_Focus Marché

### ISSUE THREAD

**Issue by FlorianChatel** [collec-data/focus-marches#33]
Bonjour à tous, 

Ci-dessous, une proposition de logo pour Focus Marché. 
C'est une version martyr, n'hésitez pas !
![camera lens illustration logo design (1)](https://github.com/collec-data/focus-marches/assets/153525706/1c23ef32-5bc3-4665-ad27-c8cdc2db47ce)

**Comment by lvinsonneau** [comment]
@FlorianChatel : tu le vendrais comment ?

**Comment by FlorianChatel** [comment]
- La loupe pour la focale 
- les couleurs rappellent celles de Arnia et Mégalis Bretagne 
- L'effet "tourbillon" qu'on retrouve dans les logos de Arnia et MB 
- Le serrage de main qu'on voit dans le logo de la SDM (toujours avec un effet tourbillon)

Un logo qui est simple dans sa conception mais facile à identifier et à décliner

**Comment by lvinsonneau** [comment]
Et question ouverte au débat : est-ce qu'on inscrit (ou pas) le libellé "focus marchés" dans le logo ?

**Comment by lvinsonneau** [comment]
Discussion en PSC : 

- diminuer le nb de couleurs 
- enlever le contour jaune pour raison d'accessibilité
- déclinaison logo avec et sans baselin "Focus marchés"

**Comment by FlorianChatel** [comment]
Nouvelles versions du logo modifiées selon vos remarques, avec et sans baseline : 


![Image](https://github.com/collec-data/focus-marches/assets/153525706/72c6c38e-4125-4b57-93b0-e55adde8f7a6)


![Image](https://github.com/collec-data/focus-marches/assets/153525706/26c8cdc3-e8a4-428d-a2d0-83ba61a94527)

**Comment by VictorVila** [comment]
Le logo a été raffiné, merci. 
On planche sur l'idée d'avoir dans la barre de menu ces éléments : 
LOGO FOCUS MARCHES (avec mention "Communauté Focus Marchés en baseline") - Eléments de menu - Logo de la structure

**Comment by FlorianChatel** [comment]
![Logo Focus Marché](https://github.com/collec-data/focus-marches/assets/153525706/07647829-0b85-4db8-bfde-1d6d482c9529)

![Logo onglet - Focus Marché](https://github.com/collec-data/focus-marches/assets/153525706/ec617b73-b0ac-4e6f-87e5-1b746bb1b89a)

**Comment by lvinsonneau** [comment]
@FlorianChatel : ne pas oublier le "s" à Focus marché**s** ;-), merci

**Comment by FlorianChatel** [comment]
[ERRATUM]

![Image](https://github.com/collec-data/focus-marches/assets/153525706/92d2ab1c-adfc-47e6-92c7-735184ed3ee6)

![Image](https://github.com/collec-data/focus-marches/assets/153525706/8ba11272-5f53-4909-a302-f062b3886573)

**Comment by djowalker** [comment]
@VictorVila @lvinsonneau 
Je n'ai pas intégré le logo avec baseline en header car la taille actuelle du logo est trop petite donc :
Un exemple d'intégration avec le logo :
![image](https://github.com/collec-data/focus-marches/assets/22080627/6b0adbb1-b6fb-44ce-afb3-e054695074c0)

Par défaut : 
![image](https://github.com/collec-data/focus-marches/assets/22080627/a4c23ce1-3101-43b1-ae56-db019abb26a0)

Footer par défaut :
![image](https://github.com/collec-data/focus-marches/assets/22080627/cce8a6bc-842c-4c2d-bf36-a498db94670e)

**Comment by lvinsonneau** [comment]
moi ça me va, merci @djowalker

**Comment by FlorianChatel** [comment]
Idem pour moi, je trouve ça très bien !

Florian CHATEL
Chargé de mission accompagnement numérique
[Salle des marchés - Datas - Numérique Responsable]
Direction Modernisation des administrations et Services numériques
________________________________
Mégalis Bretagne - Syndicat mixte de coopération territoriale
ZAC des champs blancs - 15, rue Claude Chappe - Bâtiment B
35510 CESSON-SEVIGNE
https://megalis.bretagne.bzh<https://megalis.bretagne.bzh/>** Préservons l'environnement ! N'imprimez ce courriel que si nécessaire ! **
________________________________
De : lvinsonneau ***@***.***>
Envoyé : mardi 5 mars 2024 09:54
À : collec-data/focus-marches ***@***.***>
Cc : Florian CHATEL ***@***.***>; Mention ***@***.***>
Objet : Re: [collec-data/focus-marches] Proposition Logo_Focus Marché (Issue #33)


moi ça me va, merci @djowalker<https://github.com/djowalker>

**Comment by djowalker** [comment]
Des urls à proposer pour les liens pour des clics sur les logo de chaque GIP ou Megalis ou on ne rend pas cliquable le logo ?
Sachant que le logo Focus est un bouton "home/accueil" qui renvoi sur la page d'accueil.

**Comment by lvinsonneau** [comment]
Selon moi, c'est bien si les logo de chaque organisme renvoie vers le site web de l'organisme : pour Mégalis Bretagne : https://www.megalis.bretagne.bzh/
Merci.

**Comment by VictorVila** [comment]
@FlorianChatel merci pour ce partage. Je comprends que là où l'on voit "Solaere", on verra le logo de chaque GIP ?

**Comment by djowalker** [comment]
> Le logo a été raffiné, merci. On planche sur l'idée d'avoir dans la barre de menu ces éléments : LOGO FOCUS MARCHES (avec mention "Communauté Focus Marchés en baseline") - Eléments de menu - Logo de la structure

D'après ce qui a été énoncé ici oui c'est l'idée
