### ISSUE TITLE
Déploiement automatique de la branche develop en préprod mégalis à partir d'une validation de pull request 

### ISSUE THREAD

**Issue by VictorVila** [collec-data/focus-marches#35]
Déploiement automatique de la branche develop en préprod mégalis à partir d'une validation de pull request 
Temporalité : quotidienne

**Comment by lvinsonneau** [comment]
adresse préprod Mégalis : https://data-preprod.megalis.bretagne.bzh/focus-marches/index.php

**Comment by yguenneugues** [comment]
Mise en place du déploiement automatique sur la preprod megalis,  tous les jours à 06h le matin de la version develop de github
