### ISSUE TITLE
[ATELIER UX] - Page fournisseurs - Ajout d'un lien

### ISSUE THREAD

**Issue by lvinsonneau** [collec-data/focus-marches#4]
Les acheteurs interrogés en atelier UX design ont fait remonter le souhait de se voir ajouter un lien vers l'[annuaire des entreprises](https://annuaire-entreprises.data.gouv.fr/) pour avoir facilement plus de détails sur un fournisseurs.

Exemple de la forme de l'URL sur le SIREN 071501936 : 
https://annuaire-entreprises.data.gouv.fr/entreprise/071501936

**Comment by VictorVila** [comment]
Cela semble utile 👍 
Il faut définir où serait placé le lien. Possibilités : 

- Page du fournisseur (serait-il à embarquer dans un widget ?)
- Tableau de fournisseurs de la page d'accueil
- Tableau de marchés de la collectivité / tableau de marchés de la recherche
- Fiche de chaque marché (accessible depuis le tableau de marchés de la recherche)
- Autres ?

**Comment by lvinsonneau** [comment]
Discussion PSC : OK pour un lien (a minima) qui ouvre un nouvel onglet. On verra plus tard pour une iframe intégrée

**Comment by djowalker** [comment]
Une proposition pour les écrans titulaires.php : 

![image](https://github.com/collec-data/focus-marches/assets/22080627/a8dd90f2-d984-4b09-942c-5c6e34f59e77)

Une proposition pour l'écran titulaire.php : 
![image](https://github.com/collec-data/focus-marches/assets/22080627/5e88d719-e80d-42d0-8350-7b511dd99700)

**Comment by djowalker** [comment]
https://github.com/collec-data/focus-marches/pull/34

**Comment by lvinsonneau** [comment]
OK pour moi !

**Comment by lvinsonneau** [comment]
testé ce matin en pré-prod : c'est OK 👍

**Comment by ElodieTessier** [comment]
Suite à la recette de ce matin sur la PP, je valide aussi !

**Comment by VictorVila** [comment]
Nickel, merci.
Belle utilisation du logo par ailleurs.

**Comment by lvinsonneau** [comment]
OK, merci de ton retour @VictorVila .
On les passe en tester et validées alors ?
