### ISSUE TITLE
Modification affichage sélection dates 

### ISSUE THREAD

**Issue by djowalker** [collec-data/focus-marches#47]
Modification en :
![image](https://github.com/collec-data/focus-marches/assets/22080627/7233c472-8eec-4210-acc3-4352c6d8c5f6)

@VictorVila

**Comment by djowalker** [comment]
![image](https://github.com/user-attachments/assets/14836dce-b513-498e-827b-c82a745d3189)

**Comment by lvinsonneau** [comment]
@djowalker : je commence à avoir un doute car à chaque fois que je teste une issue corrigée, je ne vois pas la modif sur [https://](https://data-preprod.megalis.bretagne.bzh/focus-marches/)

En même temps, je ne me rappelle plus de la demande d'origine, donc je passe mon tour pour la tester.
@VictorVila : cela te dit qqchose ?

**Comment by djowalker** [comment]
> @djowalker : je commence à avoir un doute car à chaque fois que je teste une issue corrigée, je ne vois pas la modif sur [https://](https://data-preprod.megalis.bretagne.bzh/focus-marches/)
> 
> En même temps, je ne me rappelle plus de la demande d'origine, donc je passe mon tour pour la tester. @VictorVila : cela te dit qqchose ?

@lvinsonneau J'ai l'impression que les modifs n'ont pas été déployé, je suis en train de chercher

**Comment by djowalker** [comment]
@lvinsonneau Nouvelle version redéployée

**Comment by lvinsonneau** [comment]
@djowalker : c'est opérationnel merci.
Je laisse @VictorVila nous dire si cela lui convient puisque, de mémoire, il était à l'origine de la demande

**Comment by VictorVila** [comment]
Nickel, merci
