### ISSUE TITLE
Graphique "La distribution par catégorie principale d'achat" de la page d'accueil

### ISSUE THREAD

**Issue by ElodieTessier** [collec-data/focus-marches#50]
Je viens de faire la recette de Focus Marchés en production de la version 2.6.2, le graphique **"La distribution par catégorie principale d'achat"** de la page d'accueil est vide.
<img width="644" alt="2024-04-24 11_09_29-Données essentielles du profil d'acheteur de Mégalis Bretagne — Mozilla Firefox" src="https://github.com/collec-data/focus-marches/assets/97222408/eda16c89-9cf6-4a12-bf55-d516735f2604">

**Comment by lvinsonneau** [comment]
Test recette en pré-prod, pour moi les graphiques sont toujours vides : 
 ![Image](https://github.com/user-attachments/assets/ae678e08-234c-4738-986d-b7f68eef3e82)

**Comment by djowalker** [comment]
@lvinsonneau La dernière version vient d'être redéployée.

**Comment by lvinsonneau** [comment]
@djowalker C'est OK, cette fois-ci : 
![image](https://github.com/user-attachments/assets/82a68734-0eb2-489c-87ca-4ce0f568f59c)
