### ISSUE TITLE
Page acheteur - Bug du widget [Indicateurs-clés] quand on filtre sur une période 

### ISSUE THREAD

**Issue by lvinsonneau** [collec-data/focus-marches#51]
Bonjour,

Sur une page acheteur donnée, si on filtre sur une période données et que l'on utilise le widget [Indicateurs-clés], la durée calculée (Période) n'est pas la bonne.
Ex. j'ai filtré sur une période de 6 mois ici : https://data.megalis.bretagne.bzh/focus-marches/acheteur.php?i=20007066200016&date_min=2023-11-14&date_max=2024-06-06

Je copie/colle le code du widget des Indicateurs-clés : 
<iframe src="https://data.megalis.bretagne.bzh/focus-marches/acheteur.php/../widget-acheteur-indicateurs.php?i=20007066200016&date_min=2023-11-14&date_max=2024-06-06&widget=1" referrerpolicy="strict-origin-when-cross-origin" style="border: 0;" width="100%" height="600px"></iframe>

J'obtiens une période de 41 mois (au lieu de 6 mois) : 
![image](https://github.com/collec-data/focus-marches/assets/2498403/03e09a88-851e-4840-a165-20d1d5132d3b)

**Comment by lvinsonneau** [comment]
Test recette en préprod : dans la page du site, OK la date est bien corrigée : 
![image](https://github.com/user-attachments/assets/6a124f11-d250-4b01-8a17-14f30509a621)


Mais quand je copie/colle le code iframe et que je le teste, la durée n'est pas corrigée : 
![image](https://github.com/user-attachments/assets/9840ad8f-671c-421e-8046-b24decb13ccd)

**Comment by djowalker** [comment]
@lvinsonneau à restester avec la version déployée

**Comment by lvinsonneau** [comment]
@djowalker Voici le code iframe ressorti qui ne marche pas (tjs en pré-prod) : 
<script>document.addEventListener("DOMContentLoaded", function () { function sendHeight() { var h = document.body.scrollHeight; window.parent.postMessage({ height: h }, "*") } window.addEventListener("message", function (e) { var t = document.getElementById("dynamic-iframe-acheteur-indicateurs"); if (e.data.height) { var newHeight = Math.max(600, Math.min(2000, e.data.height)); t.style.height = newHeight + "px"; if (newHeight <= 2000) { t.style.overflow = "hidden"; } else { t.style.overflow = "auto"; } } }, !1); sendHeight(); window.onresize = sendHeight });</script><iframe id="dynamic-iframe-acheteur-indicateurs" src="https://data-preprod.megalis.bretagne.bzh/focus-marches/acheteur.php/../widget-acheteur-indicateurs.php?i=20007066200016&date_min=2023-11-14&date_max=2024-06-06&widget=1" referrerpolicy="strict-origin-when-cross-origin" style="border: 0;" overflow-y: hidden width="100%"</iframe>

**Comment by djowalker** [comment]
@lvinsonneau 
Il manque à priori une fermeture du tag iframe, je vais corriger

Correction ci dessous 
```
<script>document.addEventListener("DOMContentLoaded", function () { function sendHeight() { var h = document.body.scrollHeight; window.parent.postMessage({ height: h }, "*") } window.addEventListener("message", function (e) { var t = document.getElementById("dynamic-iframe-acheteur-indicateurs"); if (e.data.height) { var newHeight = Math.max(600, Math.min(2000, e.data.height)); t.style.height = newHeight + "px"; if (newHeight <= 2000) { t.style.overflow = "hidden"; } else { t.style.overflow = "auto"; } } }, !1); sendHeight(); window.onresize = sendHeight });</script><iframe id="dynamic-iframe-acheteur-indicateurs" src="https://data-preprod.megalis.bretagne.bzh/focus-marches/acheteur.php/../widget-acheteur-indicateurs.php?i=20007066200016&date_min=2023-11-14&date_max=2024-06-06&widget=1" referrerpolicy="strict-origin-when-cross-origin" style="border: 0;" overflow-y: hidden width="100%"></iframe>
```

**Comment by djowalker** [comment]
@lvinsonneau la dernière version est dispo

**Comment by lvinsonneau** [comment]
@djowalker : ça marche mais le code est un peu bizarre
<script>document.addEventListener("DOMContentLoaded", function () { function sendHeight() { var h = document.body.scrollHeight; window.parent.postMessage({ height: h }, "*") } window.addEventListener("message", function (e) { var t = document.getElementById("dynamic-iframe-acheteur-indicateurs"); if (e.data.height) { var newHeight = Math.max(600, Math.min(2000, e.data.height)); t.style.height = newHeight + "px";} }, !1); sendHeight(); window.onresize = sendHeight });</script><iframe id="dynamic-iframe-acheteur-indicateurs" src="https://data-preprod.megalis.bretagne.bzh/focus-marches/acheteur.php/../widget-acheteur-indicateurs.php?i=24290031400012&date_min=2022-02-01&date_max=2024-09-20&widget=1" referrerpolicy="strict-origin-when-cross-origin" style="border: 0;" width="100%"></iframe>

Et l'aperçu est réduit (avec barre d'ascenseur) : 
![image](https://github.com/user-attachments/assets/bff5e4fa-cd68-46c4-8470-9db52c3c32ab)

C'est normal ?

**Comment by djowalker** [comment]
Le code est ainsi pour tenter de repondre à #48 afin d'adapter la taille en fonction de la page où c'est intégré. Une ballse script a été rajouté pour tenter de répondre à ça

**Comment by lvinsonneau** [comment]
OK merci, du coup, je m'interroge sur le bienfondé de la demande #48  sur le fait d'adapter la taille en fonction de la page. J'ai peur que ce qu'on gagne d'un côté, on le perde de l'autre. 
D'autres avis ?
On en parle au prochain PSC ?

**Comment by ElodieTessier** [comment]
On peut en parler au prochain PSC pour discuter de la meilleure option.
