### ISSUE TITLE
[ATELIER UX] - Pouvoir sélectionner une année ou une période donnée

### ISSUE THREAD

**Issue by lvinsonneau** [collec-data/focus-marches#9]
Les acheteurs interrogés en atelier UX design ont fait remonter le besoin de filtrer/rendre interactif les graphiques et chiffres clés de Focus marchés en sélectionnant, non pas l'ensemble de la période proposée par défaut, mais en ayant la possibilité : 

- de sélectionner une année
- de rentrée la date de début et de fin de la période qu'ils souhaitent regarder plus précisément

**Comment by VictorVila** [comment]
Bonjour, 
Cette capacité existe : 
- au niveau de la page de recherche en dépliant la recherche avancée : champs date min et date max
- sur les graphes comportant une ligne temporelle comme "Distribution par catégorie principale d'achat" : sélectionner la période souhaitée avec la souris

Il serait certes intéressant d'ajouter un filtre global pour tout l'observatoire qui concernerait la période, le territoire, etc.  mais cela nécessite une réécriture importante du code. 
A discuter :)

**Comment by Drikc7** [comment]
Bonjour,
Je pense à un contournement en partant par exemple du Widget Tous les marchés de XXX, une fois que nous sommes sous l'identité du territoire. Le widget permet une requête comme 2022 ou 2023, un tri par date au format US serait aussi facilitant.
L'application de ce filtre à tous les widget ou mieux effectivement une enclosure serait un plus appréciable. 
Bien cordialement,
CA

**Comment by lvinsonneau** [comment]
discussion du jour avec @yguenneugues  : dans un premier temps, on partirait sur le dev "simple" où on choisit une date min/max pour la totalité de la page acheteur

**Comment by djowalker** [comment]
Pas mal de dev sur cet US notamment pour bien répandre le filtrage sur chaque widget présent sur la page acheteur.

Exemple de filtrage pour la page acheteur: 
![image](https://github.com/collec-data/focus-marches/assets/22080627/0667b977-0f16-4078-80ba-2f012afd6661)

Et au format réduit : 
![image](https://github.com/collec-data/focus-marches/assets/22080627/97c14b88-a7d5-4a94-bc9c-6fb92c3f9aa7)

Le champ est un input type=date donc la sélection de date semble être native dans les navigateurs. La date est ensuite mise à jour au format US pour les requêtes.
![image](https://github.com/collec-data/focus-marches/assets/22080627/325379e1-c68a-4c04-83de-ba628945b894)

Le fait de cliquer sur filtrer recharge la page acheteur avec les champs date_min et date_max rensignés par rapport à la sélection.

L'ensemble des sous widgets sont filtrés en fonction de la date_min et la date_max.

Il est possible d'intéger un widget avec les informations de date_min et de date_max filtrées.
Il est possible de cacher le filtre sur la page acheteur lors d'une intégration en renseignant `&hide_filter=true` dans l'url de la page acheteur.

**Comment by lvinsonneau** [comment]
A tout seigneur, tout honneur, j'interroge le créateur de ce ticket : @Drikc7 qu'en penses-tu ?

**Comment by lvinsonneau** [comment]
testé en pré-prod ce matin : 

- déjà, c'est top, merci au dev  @djowalker !
- j'ai testé l'intégration de l'iframe complète : ça marche y compris avec le filtre date, top ! 👍 
- j'ai testé l'intégration unitaire des widgets : à part le 1er (Localisation et contexte), aucun ne fonctionne 👎

**Comment by djowalker** [comment]
@lvinsonneau correctifs déployés, cela devrait être mieux.

**Comment by lvinsonneau** [comment]
Nickel, testé à l'instant, c'est OK ! merci @djowalker

**Comment by djowalker** [comment]
Ajout de : https://github.com/collec-data/focus-marches/pull/42 en complément.

**Comment by lvinsonneau** [comment]
Ah oui, bien vu @djowalker !

**Comment by VictorVila** [comment]
Le filtre est très intéressant. Comme vu en PSC, nous proposons ces modifications : 

1. Placer le filtre après la section "Localisation et contexte" avant les "Indicateurs clés"
2. Ajouter au filtre la mention "Filtrez les contrats"
3. Changer "date min" contre "Date de début"
4. Changer "date max" contre "Date de fin"

Merci !

**Comment by djowalker** [comment]
Exemple : 
![image](https://github.com/collec-data/focus-marches/assets/22080627/8f7be19d-756f-449a-bf64-972e17854d37)

**Comment by lvinsonneau** [comment]
Pour moi c'est OK. @VictorVila @Thierry-RECIA  vos avis ?

**Comment by VictorVila** [comment]
@djowalker @lvinsonneau  @Thierry-RECIA 

Pour moi c'est Ok. 
A toute fin utile, je vous propose une mise en page alternative : 



![Image](https://github.com/collec-data/focus-marches/assets/2961426/af3da2ab-27b9-48da-bffc-72bb9ec4c234)

**Comment by lvinsonneau** [comment]
OK pour moi @VictorVila

**Comment by djowalker** [comment]
> @djowalker @lvinsonneau @Thierry-RECIA
> 
> Pour moi c'est Ok. A toute fin utile, je vous propose une mise en page alternative :
> 
> ![Image](https://private-user-images.githubusercontent.com/2961426/310585965-af3da2ab-27b9-48da-bffc-72bb9ec4c234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDg1MjYsIm5iZiI6MTcxMDE0ODIyNiwicGF0aCI6Ii8yOTYxNDI2LzMxMDU4NTk2NS1hZjNkYTJhYi0yN2I5LTQ4ZGEtYmZmYy03MmJiOWVjNGMyMzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMDkxMDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjNjZTQ5NDE4NmFiNjUyMzA0NGZhZmE0YWQ4NDQ4ZTE4NDE0NGMwNmVjYmY4YTM2MGU5NmQ5NDZlZGU3OTk4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5QaNYZFcQKrh_ReBLGIRg4n6lnnOwq4p5ahJJ1AV_gk)

@VictorVila Si c'est du code un moyen de commiter une branche git sur ta proposition afin de l'intégrer ?
Sinon je vais recopier visuellement.
J'ai créé l'issue #47 en lien.

**Comment by Thierry-RECIA** [comment]
Je vote pour la proposition de @VictorVila

**Comment by VictorVila** [comment]
@djowalker : malheureusement pas, c'est juste une maquette
